### ISSUE TITLE
TODO - Unit testing

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-python#13]
Add more comprehensive unit-testing as part of CI

- Download and install InvenTree instance
- Setup some test data
- Run unit tests on the API and ensure that it works!

### Tests 
- [x] Query database server `/api/` endpoint (to check the server is present)
- [x] Simple authentication using username / password
- [x] Token authentication
- [x] Read data successfully (e.g. list parts)
- [x] Cannot read data if not authenticated
- [x] Upload file attachments
- [x] Edit / Update records
- [x] Delete records
- [x] Perform stock adjustments
